backend:
  name: github
  repo: silnrsi/wstr-sample-site # Path to your GitHub repository
  branch: main
  use_graphql: true
  base_url: https://wstr.api.languagetechnology.org/
  squash_merges: true

editor:
  preview: false

media_folder: src/assets
public_folder: src/assets
publish_mode: editorial_workflow

site_url: https://silnrsi.github.io/wstr-sample-site/

collections:
- label: Guide
  name: guide
  folder: src/content/docs/guides
  create: true
  fields:
  - { label: Title, name: title, widget: string }
  - { label: Description, name: description, widget: string }
  - { label: Body, name: body, widget: markdown }
- label: Reference
  name: reference
  folder: src/content/docs/reference
  create: true
  fields:
  - { label: Title, name: title, widget: string }
  - { label: Description, name: description, widget: string }
  - { label: Body, name: body, widget: markdown }
- label: Support
  name: support
  folder: src/content/docs/support
  create: true
  fields:
  - { label: Title, name: title, widget: string }
  - { label: Description, name: description, widget: string }
  - { label: Body, name: body, widget: markdown }
- label: Topic
  name: topic
  folder: src/content/docs/topics
  create: true
  fields:
  - { label: Title, name: title, widget: string }
  - { label: Description, name: description, widget: string }
  - { label: Body, name: body, widget: markdown }
- label: Frontmatter
  name: frontmatter
  format: yaml-frontmatter
  files:
  - label: Home
    name: index
    file: src/content/docs/index.mdx
    fields:
    - { label: Title, name: title, widget: string }
    - { label: Description, name: description, widget: text, requried: false }
    - { label: Template, name: template, widget: string, requried: false }
    - label: Hero
      name: hero
      widget: object
      required: false
      fields:
      - { label: Tagline, name: tagline, widget: string }
      - label: Image
        name: image
        widget: object
        fields: [{ label: Image, name: file, widget: image, allow_multiple: false }]
      - label: Actions
        name: actions
        widget: list
        fields:
        - { label: Text, name: text, widget: text }
        - { label: Link, name: link, widget: string }
        - { label: Icon, name: icon, widget: string }
        - { label: Variant, name: variant, requried: false, widget: string }
    - { label: body, name: body, widget: markdown }
