name: Check site links

on:
  schedule:
  # Run daily at midnight
  - cron: '0 0 * * *'
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install
        run: npm install
      - name: Check Internal links
        run: |
          echo '### Link check Report' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          npm run linkcheck 2>&1 | sed -r '/ validating links /,/^$/!d'
          echo '```' >> $GITHUB_STEP_SUMMARY
